build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.17"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: health-check
  capabilities:
  - intranet
  restrict_network_access: false
  steps:
    cluster_profile: metal-perfscale-telco
    env:
      TYPE: mno
    test:
    - chain: openshift-qe-installer-bm-ping
    - chain: openshift-qe-installer-bm-load-kubeconfig
    - chain: openshift-qe-cluster-health
- always_run: false
  as: rds-core
  capabilities:
  - intranet
  restrict_network_access: false
  steps:
    cluster_profile: metal-perfscale-jetlag
    env:
      BAREMETAL: "true"
      CRUCIBLE: "false"
      LABEL: node-role.kubernetes.io/worker-dpdk,node-role.kubernetes.io/worker-metallb
      OCP_BUILD: ga
      OCP_VERSION: 4.18.5
      PUBLIC_VLAN: "true"
      SRIOV_NODE_SELECTOR: node-role.kubernetes.io/worker
      TELCO: "true"
    test:
    - ref: openshift-qe-installer-bm-ping
    - ref: openshift-qe-installer-bm-deploy
    - ref: openshift-qe-cluster-health
    - ref: openshift-qe-installer-bm-day2-label
    - ref: openshift-qe-installer-bm-day2-sriov
    - ref: openshift-qe-installer-bm-day2-metallb
    - ref: openshift-qe-installer-bm-day2-perf-profile-rds-core
    - ref: openshift-qe-rds-core
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ocp-qe-perfscale-ci
  variant: metal-telco-x86
