build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.18"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: testsecret
  steps:
    cluster_profile: metal-perfscale-jetlag
    test:
    - chain: openshift-qe-installer-bm-testsecret
    - chain: openshift-qe-installer-bm-deploy
zz_generated_metadata:
  branch: main
  org: openshift-eng
  repo: ocp-qe-perfscale-ci
  variant: metal-x86-test
