ref:
  as: openshift-qe-installer-bm-deploy
  from_image:
    namespace: ci
    name: telco-bastion
    tag: latest
  commands: openshift-qe-installer-bm-deploy-commands.sh
  credentials:
  - namespace: test-credentials # this entry injects the custom credential
    name: perfscale-metal-bastion
    mount_path: /secret
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
  - name: OCP_BUILD
    default: "ga"
    documentation: |-
     Whether the build should use 'dev' (nightly builds) or 'ga' for Generally Available version of OpenShift
  - name: OCP_VERSION
    default: "latest-4.15"
    documentation: |-
     Short Version. Values accepted: latest-4.14, explicit version i.e. 4.15.2 or for dev builds, candidate-4.16
  - name: JETLAG_PR
    default: "508"
    documentation: |-
     If defined, use a specific jetlag PR
  - name: TYPE
    default: "bm"
    documentation: |-
     BM, SNO or RWN.
  - name: NUM_WORKER_NODES
    default: "1"
    documentation: |-
      Number of worker nodes
  - name: FIPS
    default: "false"
    documentation: |-
      Enable or disable fips
  - name: CRUCIBLE
    default: "true"
    documentation: |-
      Enable or disable crucible install on the bastion