build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: deploy-5nodes
  cluster: build05
  restrict_network_access: false
  steps:
    cluster_profile: metal-perscale-cpt
    env:
      BASTION_CP_INTERFACE: eno1
      BASTION_LAB_INTERFACE: eno3
      CONTROLPLANE_LAB_INTERFACE: eno3
      CRUCIBLE: "false"
      LAB: cloud19
      NUM_WORKER_NODES: "2"
      OCP_VERSION: latest-4.17
    test:
    - chain: openshift-qe-installer-bm-ping
    - chain: openshift-qe-installer-bm-deploy
zz_generated_metadata:
  branch: main
  org: redhat-performance
  repo: jetlag
