build_root:
  image_stream_tag:
    name: ci-tools-build-root
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- always_run: false
  as: deploy-sno-jetlag-route
  capabilities:
  - intranet
  restrict_network_access: false
  steps:
    cluster_profile: metal-perscale-cpt
    env:
      CRUCIBLE: "false"
      LAB_CLOUD: cloud19
      OCP_VERSION: latest-4.17
      TYPE: sno
    test:
    - chain: openshift-qe-installer-bm-ping
    - chain: openshift-qe-installer-bm-deploy
  timeout: 7h0m0s
zz_generated_metadata:
  branch: main
  org: openshift-qe
  repo: ocp-qe-perfscale-ci
  variant: metal-x86-jetlag-route
